"""AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class CVAnalysis(StructuredContent):
    """Generated CVAnalysis class"""

    skills: str = Field(..., description="List of technical and soft skills possessed by the candidate")
    years_of_experience: float = Field(..., description="Total years of professional experience")
    education: str = Field(..., description="Educational background including degrees and institutions")
    previous_roles: str = Field(..., description="List of previous job titles and companies")
    key_achievements: str | None = Field(default=None, description="Notable accomplishments and contributions from past positions")
