"""AUTOGENERATED CODE - DO NOT EDIT

If you want to customize this structure:
  1. Copy this file to your own module
  2. Remove the 'structure' or 'refines' declaration from the concept in the MTHDS file
     and declare it in inline mode (see https://docs.pipelex.com/home/6-build-reliable-ai-workflows/concepts/define_your_concepts/#basic-concept-definition)
  3. Make sure your custom class is importable and registered

To regenerate: pipelex build structures <target_directory>
"""

from pipelex.core.stuffs.structured_content import StructuredContent
from pydantic import Field


class JobRequirements(StructuredContent):
    """Generated JobRequirements class"""

    required_skills: str = Field(..., description="Skills that are mandatory for the position")
    preferred_skills: str | None = Field(default=None, description="Skills that are desirable but not mandatory")
    responsibilities: str = Field(..., description="Main duties and tasks of the role")
    qualifications: str | None = Field(default=None, description="Required educational or professional qualifications")
    experience_level: str = Field(..., description="Expected level of experience for the role")
