name: "CLA Assistant bot"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CLA_GH_APP_ID }}
          private-key: ${{ secrets.CLA_GH_APP_PRIVATE_KEY }}
          owner: Pipelex
          repositories: |
            cla-signatures
            pipelex

      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          path-to-signatures: "signatures/version1/cla.json"
          path-to-document: "https://github.com/Pipelex/pipelex/blob/main/CLA.md"
          branch: main
          allowlist: lchoquel,thomashebrard,bot*
          remote-organization-name: Pipelex
          remote-repository-name: cla-signatures
          signed-commit-message: "$contributorName has signed the CLA in $owner/$repo#$pullRequestNo"
