

domain = "hello_world"
definition = "starter pipeline"

[pipe]
[pipe.hello_world]
PipeLLM = "Write text about Hello World."
output = "Text"
llm = { llm_handle = "gpt-4o-mini", temperature = 0.9, max_tokens = "auto" }
prompt = """
Write a haiku about Hello World.
"""

